// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ardire-styles/CinematicAtelier.tsx": () => import("../components/mockups/ardire-styles/CinematicAtelier.tsx"),
  "./components/mockups/ardire-styles/EditorialHeritage.tsx": () => import("../components/mockups/ardire-styles/EditorialHeritage.tsx"),
  "./components/mockups/ardire-styles/SalonPrive.tsx": () => import("../components/mockups/ardire-styles/SalonPrive.tsx")
};
