// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ardire-v2/ChauffeurAfter.tsx": () => import("../components/mockups/ardire-v2/ChauffeurAfter.tsx"),
  "./components/mockups/ardire-v2/HomepageAudienceSplit.tsx": () => import("../components/mockups/ardire-v2/HomepageAudienceSplit.tsx"),
  "./components/mockups/ardire-v2/LuxuryToursAfter.tsx": () => import("../components/mockups/ardire-v2/LuxuryToursAfter.tsx")
};
